export const TODO_ADD_TODO = 'TODO_ADD_TODO';
export const TODO_COMPLETE_TODO = 'TODO_COMPLETE_TODO';
export const TODO_DELETE_TODO = 'TODO_DELETE_TODO';
export const TODO_CLEAR_COMPLETED = 'TODO_CLEAR_COMPLETED';
export const TODO_COMPLETE_ALL = 'TODO_COMPLETE_ALL';
export const TODO_EDIT_TODO = 'TODO_EDIT_TODO';
